// AUTO-GENERATED by generate.py — do not edit by hand.
// Source: Obsidian forms references + unit notes + progress.json boxes.
// Empty on a fresh setup. Run `python3 generate.py` after your vault has content.
const VOCAB = [
];
